{
  "CVE Code": "CVE-2021-32492",
  "Published": "2021-06-24T18:21:02",
  "Updated": "2024-08-03T23:17:29.621Z",
  "Description": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds read in function DJVU::DataPool::has_data() via crafted djvu file may lead to application crash and other consequences.",
  "ProblemTypes": [
    "CWE-119"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "djvulibre",
      "versions": [
        "djvulibre-3.5.28 and earlier"
      ]
    }
  ],
  "Reference": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=1943686",
    "https://www.debian.org/security/2021/dsa-5032"
  ]
}