{
  "CVE Code": "CVE-2025-29606",
  "Published": "2025-07-14T00:00:00.000Z",
  "Updated": "2025-07-14T14:13:07.783Z",
  "Description": "py-libp2p before 0.2.3 allows a peer to cause a denial of service (resource consumption) via a large RSA key.",
  "ProblemTypes": [
    "CWE-770 Allocation of Resources Without Limits or Throttling"
  ],
  "Affected": [
    {
      "vendor": "libp2p",
      "product": "py-libp2p",
      "versions": [
        "0"
      ]
    }
  ],
  "Reference": [
    "https://github.com/libp2p/py-libp2p/issues/526",
    "https://github.com/libp2p/py-libp2p/pull/531/files",
    "https://github.com/libp2p/py-libp2p/compare/v0.2.2...v0.2.3"
  ]
}