{
  "CVE Code": "CVE-2020-36599",
  "Published": "2022-08-18T22:48:07",
  "Updated": "2024-08-04T17:30:08.472Z",
  "Description": "lib/omniauth/failure_endpoint.rb in OmniAuth before 1.9.2 (and before 2.0) does not escape the message_key value.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://github.com/omniauth/omniauth/commit/43a396f181ef7d0ed2ec8291c939c95e3ed3ff00#diff-575abda9deb9b1a77bf534e898a923029b9a61e991d626db88dc6e8b34260aa2",
    "https://rubygems.org/gems/omniauth/versions/1.9.2"
  ]
}