{
  "CVE Code": "CVE-2024-1141",
  "Published": "2024-02-01T14:21:37.758Z",
  "Updated": "2024-11-24T14:50:21.545Z",
  "Description": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled.",
  "ProblemTypes": [
    "Logging of Excessive Data"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "0"
      ]
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 17.1 for RHEL 9",
      "versions": [
        "0:2.5.1-17.1.20230621023901.el9ost"
      ]
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 16.1",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 16.2",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 18.0",
      "versions": []
    }
  ],
  "Reference": [
    "https://access.redhat.com/errata/RHSA-2024:2732",
    "https://access.redhat.com/security/cve/CVE-2024-1141",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2258836"
  ]
}