{
  "CVE Code": "CVE-2017-14503",
  "Published": "2017-09-17T18:00:00",
  "Updated": "2024-08-05T19:27:40.808Z",
  "Description": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://bugs.debian.org/875960",
    "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html",
    "https://www.debian.org/security/2018/dsa-4360",
    "https://usn.ubuntu.com/3736-1/",
    "https://github.com/libarchive/libarchive/issues/948",
    "https://access.redhat.com/errata/RHSA-2019:2298",
    "https://security.gentoo.org/glsa/201908-11",
    "https://access.redhat.com/errata/RHSA-2019:3698"
  ]
}