{
  "CVE Code": "CVE-2022-1431",
  "Published": "2022-05-10T20:27:54",
  "Updated": "2024-08-03T00:03:06.272Z",
  "Description": "An issue has been discovered in GitLab affecting all versions starting from 12.10 before 14.8.6, all versions starting from 14.9 before 14.9.4, all versions starting from 14.10 before 14.10.1. GitLab was not correctly handling malicious requests to the PyPi API endpoint allowing the attacker to cause uncontrolled resource consumption.",
  "ProblemTypes": [
    "Uncontrolled resource consumption in GitLab"
  ],
  "Affected": [
    {
      "vendor": "GitLab",
      "product": "GitLab",
      "versions": [
        ">=12.10, <14.8.6",
        ">=14.9, <14.9.4",
        ">=14.10, <14.10.1"
      ]
    }
  ],
  "Reference": [
    "https://gitlab.com/gitlab-org/gitlab/-/issues/262724",
    "https://hackerone.com/reports/996850",
    "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1431.json"
  ]
}