{
  "CVE Code": "CVE-2020-24583",
  "Published": "2020-09-01T12:33:13",
  "Updated": "2024-08-04T15:19:08.390Z",
  "Description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://docs.djangoproject.com/en/dev/releases/security/",
    "https://usn.ubuntu.com/4479-1/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/",
    "https://www.oracle.com/security-alerts/cpujan2021.html",
    "https://groups.google.com/forum/#%21topic/django-announce/zFCMdgUnutU",
    "https://groups.google.com/forum/#%21topic/django-announce/Gdqn58RqIDM",
    "https://www.openwall.com/lists/oss-security/2020/09/01/2",
    "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
    "https://security.netapp.com/advisory/ntap-20200918-0004/"
  ]
}