{
  "CVE Code": "CVE-2019-15032",
  "Published": "2019-09-19T16:03:06",
  "Updated": "2024-08-05T00:34:53.070Z",
  "Description": "Pydio 6.0.8 mishandles error reporting when a directory allows unauthenticated uploads, and the remote-upload option is used with the http://localhost:22 URL. The attacker can obtain sensitive information such as the name of the user who created that directory and other internal server information.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://sourceforge.net/projects/ajaxplorer/files/pydio/stable-channel/",
    "https://pydio.com",
    "https://heitorgouvea.me/2019/09/17/CVE-2019-15032"
  ]
}