{
  "CVE Code": "CVE-2019-18874",
  "Published": "2019-11-12T01:30:29",
  "Updated": "2024-08-05T02:02:39.894Z",
  "Description": "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://github.com/giampaolo/psutil/pull/1616",
    "https://lists.debian.org/debian-lts-announce/2019/11/msg00018.html",
    "https://usn.ubuntu.com/4204-1/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2P7QI7MOTZTFXQYU23CP3RAWXCERMOAS/",
    "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OLETTJYZL2SMBUI4Q2NGBMGPDPP54SRG/"
  ]
}