{
  "CVE Code": "CVE-2019-5010",
  "Published": "2019-10-31T20:05:57",
  "Updated": "2024-08-04T19:40:49.196Z",
  "Description": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
  "ProblemTypes": [
    "CWE-476: NULL Pointer Dereference"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "Python",
      "versions": [
        "Python.org CPython 2.7.11 Python.org CPython 3.6.6 Python.org CPython 3.5.2 Python.org CPython 3 master at 480833808e918a1dcebbbcfd07d5a8de3c5c2a66"
      ]
    }
  ],
  "Reference": [
    "https://access.redhat.com/errata/RHSA-2019:3520",
    "https://access.redhat.com/errata/RHSA-2019:3725",
    "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html",
    "https://security.gentoo.org/glsa/202003-26",
    "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html",
    "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E",
    "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html",
    "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758"
  ]
}